title: Cole Humes # your name (or website title) here
logo: "/images/Screen Shot 2018-12-29 at 10.39.15 PM.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)   
  <br>
  Useful Links: 
  <br><br>
  <a href="https://www.linkedin.com/in/cole-humes-6b9835191/">LinkedIn</a> 
  <br>
  <a href="https://crh222.github.io/colehumes.github.io/measure_risk">Portfolio</a>  
  <br>  
  <a href="https://github.com/crh222/">GitHub</a>  
  <br>
  
theme: jekyll-theme-minimal
